### ISSUE TITLE
Multiple $GOPATHs?

### ISSUE THREAD

**Issue by ilyaglow** [kennyp/asdf-golang#1]
Hey there, I'm stucked with the problem: how could I use different go versions with different packages and imports to archieve some kind of gemsets that ruby can do.

I have an idea of changing `$GOPATH` env variable when I switch to different go version but I can't figure out what the actual path might be. Probably like:
 `$ASDF_INSTALL_PATH/../projects` ?

Maybe we should handle `$GOPATH` globally from exec-env script to avoid going to `~/.asdf/install/go/version/projects` and make us capable of just doing `cd $GOPATH`? Like create `~/.gopathrc` and make it called from `~/.profile` and parse first one each time exec-env is called...

Maybe you have another thoughts/suggestion/solution?

Thanks!

**Comment by kennyp** [comment]
I think #2 should get you what you need unless I'm misunderstanding what you are looking for.
