### ISSUE TITLE
Integration with other tools

### ISSUE THREAD

**Issue by iJebus** [kennyp/asdf-golang#15]
How are other people handling integration with other tools, .e.g, vim-go? Running commands like `:GoInstallBinaries` are fine because they run `go` and then figure out the `GOPATH`, but `:GoDef` expects a `GOROOT` and fails. Not saying that this is an issue for this tool to resolve, just presumably I'm not the first person to run into this problem.

**Comment by kennyp** [comment]
@iJebus I usually use something like [direnv](https://direnv.net/) to set env vars for each project. You can even do something like

```bash
go env | grep '^\(GOPATH\|GOROOT\)=' | sed -e 's/^/export /' >> .envrc
direnv allow .
```

if you just want to use the defaults.

**Comment by iJebus** [comment]
Nice one.
