### ISSUE TITLE
setting $PATH for installed versions

### ISSUE THREAD

**Issue by trinode** [kennyp/asdf-golang#18]
Is there any way we could have the $PATH environment variable modified to include the bin folder from the go packages folder based on the selected version?

Eg if you install realize: 

`go get github.com/tockins/realize`

it creates a binary: 
`~/.asdf/installs/golang/1.10/packages/bin/realize`

and you should be able to simply run the command `realize` (but you can't since the `<selected go version>/packages/bin` folder isn't in the path

**Comment by kennyp** [comment]
Hey @trinode,

I believe if you run `asdf reshim golang` you should be able to use `realize`. It's a shim thing, not a `$PATH` thing.

Thanks,
-Kenny

**Comment by yofriadi** [comment]
Hi I think this needs to get highlighted in README, because it doesnt work out of the box like nodejs did with npm.

Thank you
