### ISSUE TITLE
Starting the environment doesn't add versions bin to path

### ISSUE THREAD

**Issue by austince** [kennyp/asdf-golang#20]
Can't access install go package executables.

Running on Ubuntu 16.04.
asdf v0.4.2

Steps to reproduce:
- Install a `<version>` of go
- `asdf local golang <version>` or `asdf global golang <version>`, doesn't matter
- `go get -u <some package>`
- Try to run that package

Tried with version 1.4, 1.5, 1.9 with the package `mvdan.cc/sh/cmd/shfmt`

**Comment by saschahemleb** [comment]
Hey,

you probably need to reshim, did you try running `asdf reshim golang`?
