### ISSUE TITLE
cannot find GOROOT directory: /usr/lib/go

### ISSUE THREAD

**Issue by feluxe** [kennyp/asdf-golang#23]
**Describe the bug**

I installed `asdf-golang`. When I run a `go` command I get an error.

**To Reproduce**

1. `$ asdf plugin-add golang https://github.com/kennyp/asdf-golang.git`
2. `$ asdf install golang 1.12.1`
3. `$ asdf global golang 1.12.1`
4. `$ go run myfile.go`

Error:
>
> go: cannot find GOROOT directory: /usr/lib/go
>

**Expected behavior**

I expected go to work without the error.

**Desktop (please complete the following information):**

 - OS:  `Arch Linux`
 - Version `asdf v0.7.0`

**Comment by homburg** [comment]
@feluxe Do you still have the issue? Can you supply the output of these commands for debug:

`env | grep GOROOT`
`which go`
`go env GOROOT`

**Comment by feluxe** [comment]
Thanks for your reply!

> Do you still have the issue?

Strange...I haven't changed anything since I reported, but I just tried again and it works now. So I think the issue was on my side. Sorry!

Anyways... I leave the output of your commands here, in case anyone runs into the same issue:

```
$ env | grep GOROOT
# Returns nothing
```

```
$ which go
/home/peter/.asdf/shims/go
```

```
$ go env GOROOT
/home/peter/.asdf/installs/golang/1.11.6/go
```

Hope it helps...

**Comment by homburg** [comment]
You're welcome! Thanks for the update. 

Everything looks correct, might have been a PATH/rehash issue

**Comment by ferismed** [comment]
I have the same issue
can somenody help me
 I have this results:
go build main.go
go: cannot find GOROOT directory: /usr/lib/go

env | grep GOROOT
GOROOT=/usr/lib/go

which go
/usr/local/go/bin/go

 go env GOROOT
go: cannot find GOROOT directory: /usr/lib/go

**Comment by jaimem88** [comment]
> I have the same issue
> can somenody help me
> I have this results:
> go build main.go
> go: cannot find GOROOT directory: /usr/lib/go
> 
> env | grep GOROOT
> GOROOT=/usr/lib/go
> 
> which go
> /usr/local/go/bin/go
> 
> go env GOROOT
> go: cannot find GOROOT directory: /usr/lib/go

@ferismed Restarting the shell worked for me

**Comment by harsh-kk** [comment]
> @feluxe Do you still have the issue? Can you supply the output of these commands for debug:
> 
> `env | grep GOROOT`
> `which go`
> `go env GOROOT`

env | grep GOROOT                                                                                             2 ⨯
GOROOT=/usr/lib/go

which go
/usr/local/go/bin/go

go env GOROOT
go: cannot find GOROOT directory: /usr/lib/go

#need_help

**Comment by pokstad** [comment]
I'm also running into this. I have a workaround in my `.zshrc`:

```
export GOROOT=$(asdf where golang)/go
```

However, this will break anytime I change directory somewhere that has a new `.tool-versions` file.
