### ISSUE TITLE
Regex missing patch in version number

### ISSUE THREAD

**Issue by jesse-c** [kennyp/asdf-golang#4]
When running `asdf list-all golang` it includes results such as `1.7.freebsd-amd64` which is missing the patch number. It should be `1.7.3.freebsd-amd64`

**Comment by kennyp** [comment]
The patch version not showing was fixed with #7 although, the install script doesn't support freebsd yet. I'm working on a fix for that separately. Thanks!

**Comment by jesse-c** [comment]
Sounds good, thanks for your work!

**Comment by kennyp** [comment]
@jesse-c Not sure if you're actually using FreeBSD, but 0199441 allows for it. If you're on a BSD system I would appreciate it if you could test it out and let me know if you have any issues.

**Comment by jesse-c** [comment]
It's been a while since I've touched my FreeBSD box where I think I was using it! If I find some time I'll try and test it out and let you know.
