### ISSUE TITLE
Any reason list-all versions can't be obtained from 'github.com/golang/go' or 'go.googlesource.com/go/+refs'?

### ISSUE THREAD

**Issue by cho-m** [kennyp/asdf-golang#48]
I was originally looking at this because `asdf latest golang` (which uses `list-all` internally) is noticeably slower than some of my other asdf plugins. Looking at some hyperfine benchmarks, I see it takes around 5s to complete compared to nodejs (0.5s) and python/ruby (60ms).

I assume part of that is the extra processing for truncated data + XML handling.

I was wondering if asdf-golang could just access tags from one of golang's repos.

Looking at how some alternative version managers do this:
* [gvm](https://github.com/moovweb/gvm) - logic using `git ls-remote -t  https://github.com/golang/go`,
  - https://github.com/moovweb/gvm/blob/19365a6ab8ac4920234b2612c529eed2373299db/scripts/listall#L35
  - this implementation uses `git` and `awk` (both extra dependencies). `awk` can usually be replaced with other tools. `git` would depend on whether golang exposes data via GitHub API (`curl`-able)
  - logic is much simpler, which should also mean easier maintenance.
  - A basic variant of above combined with existing asdf-golang logic runs on my system in ~0.5s
      ```bash
      git ls-remote --tags https://github.com/golang/go "go*" \
        | awk -F/go '{ print $2 }' \
        | uniq \
        | sort -t. -k 1,1 -k 2,2n -k 3,3n -k 4,4n -k 5,5n \
        | tr '\n' ' '
      ```
  - **EDIT**: Another variant using GitHub API thru `curl`, `grep`, `sed` runs in ~0.25s.  A couple asdf plugins that use GitHub API usually add logic for optionally using `GITHUB_API_TOKEN` probably to increase GitHub rate limits.
      ```
      curl --silent --location "https://api.github.com/repos/golang/go/git/refs/tags" \
          | grep '"ref".*go' \
          | mysed 's/.*go([0-9].*)",/\1/' \
          | uniq \
          | sort -t. -k 1,1 -k 2,2n -k 3,3n -k 4,4n -k 5,5n \
          | tr '\n' ' '
      ```

* [g](https://github.com/stefanmaric/g) - logic using `curl --silent --location "https://go.googlesource.com/go/+refs"`
  - https://github.com/stefanmaric/g/blob/1a9a135d07975c2ba804ddfae9a4089c9773ffe4/bin/g#L348
  - this implementation uses `curl` and `grep`/`tr` (same dependencies).
  - logic is again much simpler
  - A variant using the defined `mysed` runs on my system in ~0.4s.
      ```bash
      curl --silent --location "https://go.googlesource.com/go/+refs" \
        | grep -E -o '"/go/\+/refs/tags/go.+?"' \
        | mysed 's/.*go([0-9].*)"$/\1/' \
        | uniq \
        | sort -t. -k 1,1 -k 2,2n -k 3,3n -k 4,4n -k 5,5n \
        | tr '\n' ' '
      ```

Comparing the output, it looks like the above options include some older versions of go from v1 up to v1.2.1.

**Comment by kennyp** [comment]
:thinking:  The reason for working from the bucket to begin with so we could be sure it's available to download from `dl.google.com`. What are your thoughts on how we would avoid listing tagged versions that aren't available?

**Comment by cho-m** [comment]
I think the main issue is old versions (I previously saw v1 up to v1.2.1, which I don't think are available to download).
I don't know how often newer tags have issues.
May need to see if the bucket and git repos are updated in-sync.

---

Currently, using the bucket does have its own quirks.
For example, it is showing some versions that probably shouldn't be accessed:
```
.dmitshur_apr1_v0/go1.15.11
.dmitshur_apr1_v0/go1.16.3
1.15.12_amedee_v1/go1
```

---

Also, some of the currently listed versions may not be installable depending on hardware/architecture.
For example, the oldest listed version 1.2.2 probably cannot be accessed on Mac via asdf-golang:
- I think it will try non-existent: https://dl.google.com/go/go1.2.2.darwin-arm64.tar.gz 
- Instead need to access: https://dl.google.com/go/go1.2.2.darwin-amd64-osx10.8.tar.gz
   (with some tedious logic like GVM, which is probably broken with Big Sur [11.x] release: https://github.com/moovweb/gvm/blob/master/scripts/install#L159-L163)

---

I think the simplicity/maintainability/speed of the git repo tags outweighs the demerits of listing some very old, non-installable versions (which could possibly be filtered out).

Though, this is my opinion, so will let others comment further.

**Comment by trallnag** [comment]
How about introducing a very basic form of caching? Writing the already processed data to something like `~/.cache` and loading it when the checksum of the downloaded non-processed data matches a key stored next to the cached data.

Though I don't know if its the processing of the XML that takes the most time and if pickling the processed data within Bash can be easily done
