### ISSUE TITLE
Dynamically setting $GOROOT based on go version in use.

### ISSUE THREAD

**Issue by sadir** [kennyp/asdf-golang#5]
Hi, 

When installing go via asdf-golang, I have found you need to update your `$GOROOT` environment variable as by default Go expects to be installed in `/usr/local/go/`, but asdf installs it into `~/.asdf/shims/go` (well, `~/.asdf/installs/golang/` really).

Can we have `$GOROOT` automatically updated based on the go version in use in the project?

For how I discovered this, please see [this issue](https://github.com/DATA-DOG/godog/issues/64#issuecomment-319153610).

**Comment by sadir** [comment]
For anyone who stumbles across this, [here](https://github.com/sadir/bash-config/blob/master/etc/profile.d/golang.sh) is how I got around this problem.

**Comment by bradylove** [comment]
This would be really convenient to have.

@sadir your link for the work around is giving a 404. Do you still have that somewhere?

**Comment by sadir** [comment]
@bradylove Good point - I've updated the link above.

**Comment by kennyp** [comment]
I believe this was fixed by https://github.com/kennyp/asdf-golang/pull/2.

Let me know if you're still having issues.

**Comment by kunthar** [comment]
> For anyone who stumbles across this, [here](https://github.com/sadir/dotfiles/blob/8c3594003930d7f0d8c3ad245f147146fef303c6/.exports.sh) is how I got around this problem.

i propose a small advancement:
```
GOV=$(asdf current golang | awk '{print $1}')
```

**Comment by robododge** [comment]
#Use the "where" command  
GOV=$(asdf where golang)
export GOROOT=$GOV/go

**Comment by BaptisteLalanne** [comment]
For those who still have the issue you don't need the line above (plus it won't change dynamically if you change folders) it is already handle by asdf-golang.

The reason it might not work for you is probably that you set $GOPATH in your .bashrc/.zshrc. Remove any hardcoded value of $GOROOT, $GOPATH and try again
