### ISSUE TITLE
No go executable found for golang system

### ISSUE THREAD

**Issue by nikhilgeo** [kennyp/asdf-golang#51]
**Describe the bug**
Installed latest golang with asdf but go executable cannot be found.

~ $ asdf version
v0.8.0
~ $ asdf install golang latest
~ $ go version
go version go1.16.4 darwin/amd64
~ $ cd ~/Test/
Test $ go version
No go executable found for golang system

**Expected behavior**
go executable could be found from any folder.

**Comment by kennyp** [comment]
Hey @nikhilgeo, did you try setting `asdf local golang 1.16.4` or `asdf global golang 1.16.4`?

**Comment by kennyp** [comment]
I assume you're all good and I'll close this for now.
