### ISSUE TITLE
Go install don't work

### ISSUE THREAD

**Issue by schweigert** [kennyp/asdf-golang#53]
**Describe the bug**

$GOPATH and $GOROOT isn't correctly started when install, use or select a go version using asdf-golang.
Executables can't run because $GOPATH and $GOROOT isen't setted.

**To Reproduce**

Run this steps:

```
asdf install golang 1.16.4
go get -v github.com/rubenv/sql-migrate/...

sql-migrate
zsh: command not found: sql-migrate
```

**Expected behavior**

sql-migrate must be accessible.

**Comment by kennyp** [comment]
Have you done a reshim?

https://github.com/kennyp/asdf-golang/#when-using-go-get

**Comment by kennyp** [comment]
I'm going to assume you forgot to reshim or got it figured out otherwise. Feel free to re-open if you're still having issues.
