### ISSUE TITLE
go1.17.7.darwin-arm64.tar.gz returned status 404 (not found)

### ISSUE THREAD

**Issue by willduarte** [kennyp/asdf-golang#69]
**Describe the bug**
I tried to install the 1.17.7 version from asdf golang plugin and got the message.

```bash
$ asdf install golang 1.17.7
Platform 'darwin' supported!
URL: https://dl.google.com/go/go1.17.7.darwin-arm64.tar.gz returned status 404
```

**To Reproduce**
1. Run the install command

**Expected behavior**
OK result and the version listed by `asdf list golang` command

**Comment by dgalmeida** [comment]
Same issue here, weird cuz the download urls seems exactly of [google](https://go.dev/dl/) page.

**Comment by kennyp** [comment]
It looks like there is a bit of time between when a release is tagged and when it's actually available. I added a [latest-stable](https://github.com/kennyp/asdf-golang/blob/master/bin/latest-stable) script to avoid picking up a version that wasn't available yet, but I didn't change `list-all` to do a similar check. Shouldn't be too hard.

**Comment by kennyp** [comment]
@willduarte or @dgalmeida I assume you can both install `1.17.7` now?

**Comment by dgalmeida** [comment]
Yep! That works fine... Thanks for you job! By the way, to try an old version (< 1.16 ) leads to 404 also. Whiteout saying that darwin-arm64 isn't compiled available before 1.16.

**Comment by kennyp** [comment]
Yeah, I think I should probably do some sort of cache where I validate all of the combinations of arch, os, and version in order to eliminate those sorts of cases as well.

**Comment by matino** [comment]
I get the same error when downloading 1.18.0 version:
```
» asdf install golang 1.18.0
Platform 'darwin' supported!
URL: https://dl.google.com/go/go1.18.0.darwin-amd64.tar.gz returned status 404
```

**Comment by willduarte** [comment]
thanks @kennyp !
@matino try to install as `asdf install golang 1.18`

**Comment by matino** [comment]
@willduarte that did the trick, thanks a lot!
