### ISSUE TITLE
Go cli not working

### ISSUE THREAD

**Issue by rubiin** [kennyp/asdf-golang#71]
**Describe the bug**
tried `go get github.com/pilu/fresh` and `fresh`. Got command `fresh` not found

**To Reproduce**
1. Install andy cli via go get and run the cli

**Expected behavior**
Cli should e invoked

**Screenshots**
Screenshot: https://i.imgur.com/D9UU7Pv.png

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by rubiin** [comment]
@kennyp ?

**Comment by kennyp** [comment]
@rubiin I've been hesitant to add more overhead by doing more with shims and instead I've been using [asdf-direnv](https://github.com/asdf-community/asdf-direnv) to avoid shims all together.  There's a note in the README about needing to reshim, and I could add a note to look at `asdf-direnv`. Thoughts?
