### ISSUE TITLE
ASDF-Go Picking Incorrect Go Version from go.mod

### ISSUE THREAD

**Issue by MESMUR** [kennyp/asdf-golang#79]
**Describe the bug**
My asdf-golang installation seems to be picking the wrong go version for a project.
It is:
a) Picking the version from the go.mod file that is present, but the incorrect version
b) Ignoring the .tool-versions file present in the parent directory 

I suppose b) is normal behavior IF the go.mod file takes precedence over .tool-versions present in the closest parent directory.

**To Reproduce**
1. mkdir project
2. cd project
3. asdf local golang 1.17
4. mkdir test
5. cd test
6. go version > 1.17 (as expected
7. go mod init test
8. go version > 1.18 

in 8, asdf current takes the go version from the go.mod file, but the go.mod file shows 1.17

**Expected behavior**
asdf-go picks the correct version from the go.mod file and remains at v1.17

**Screenshots**
![image](https://user-images.githubusercontent.com/22883661/164134056-1eb88bbe-eba4-4738-808b-223ec1950760.png)

**Desktop (please complete the following information):**
 - OS: WSL2 on Windows 11
 - Browser: Firefox

**Comment by jhchabran** [comment]
@MESMUR landed here as I was facing the same issue. Fixed it by removing the `legacy_version_file = yes` from `~/.asdfrc` if that can help.

**Comment by MESMUR** [comment]
Thanks @jhchabran, that resolved the issue for me. I'll close the issue ;)
