### ISSUE TITLE
`asdf list-all golang` is broken

### ISSUE THREAD

**Issue by mdesantis** [kennyp/asdf-golang#8]
Plugin just installed.

When I run `asdf list-all golang` I get this error:

```
> asdf list-all golang 
: invalid option namelugins/golang/bin/list-all: line 2: set: pipefail
```

**Comment by kennyp** [comment]
Hey @mdesantis, I'm not able to reproduce on any of my machines. Can you give me particulars on what OS and such that you're using?

**Comment by mdesantis** [comment]
Hi @kennyp , I was using fish shell on Ubuntu 16.04, but on this pc it works now. I'll check on the other PC and let you know more details

**Comment by kennyp** [comment]
Hey @mdesantis, I haven't tried fish in a while. I used Ubuntu 16.04 on my work box. I'll give it a try with fish there and see what happens.

**Comment by kennyp** [comment]
So, it didn't fail on my box with fish either, but I did do a little digging and found out that since `pipefail` wasn't available until Bash v3 it could be that using an older version of bash would cause that error.

In commit d34f928 I added a check for Bash version that should fix this.
