### ISSUE TITLE
`go get -u $PACKAGES` deprecated

### ISSUE THREAD

**Issue by Jordhan-Carvalho** [kennyp/asdf-golang#85]
**Describe the bug**
Can't get the default packages to be installed by following the readme... `go get` is deprecated, it is supposed to be using `go install`, tried to figure out how to do it with go install but my knowledge in go is really limited (just getting started)

**To Reproduce**

1 - Follow the README `Default go get packages` section
2 - Error message
```
go: go.mod file not found in current directory or any parent directory.
	'go get' is no longer supported outside a module.
	To build and install a command, use 'go install' with a version,
	like 'go install example.com/cmd@latest'
	For more information, see https://golang.org/doc/go-get-install-deprecation
	or run 'go help get' or 'go help install'.
```

**Expected behavior**
The default packages being installed.

**Additional context**
Tried to figure out how to make it work to update de README.md myself but failed... Thank you for the plugin

**Comment by Xilis** [comment]
I think you just need to update your plugin, `asdf plugin update --all`.

https://github.com/kennyp/asdf-golang/blob/master/bin/install#L47 shows that both `go install` and `go get -u` are supported based on the go version

**Comment by kennyp** [comment]
Thanks for responding @Xilis!

@Jordhan-Carvalho if the update doesn't fix it, feel free to re-open and I can dig in more.
