### ISSUE TITLE
Does not respect the `${HOME}/.tool-versions` or `${HOME}/.go-version`

### ISSUE THREAD

**Issue by chenrui333** [kennyp/asdf-golang#86]
I just found out an issue that somehow the plugin does not respect the config files in the user home directory, but it does respect the config files in the project directory.

Not quite sure what caused the issue, (I am using the latest `asdf`, installed via `brew`). Thanks!

```
$ asdf --version
v0.10.2
```

**Comment by kennyp** [comment]
@chenrui333 I can't reproduce this issue. And I don't actually do anything with those myself. Can you give me the output when you run `asdf info` and `asdf current`?

**Comment by kennyp** [comment]
I was never able to re-produce. Please feel free to re-open if you run into the issue again.
