### ISSUE TITLE
Versions prior to 1.5.4 don't have checksum files available, which renders them impossible to install

### ISSUE THREAD

**Issue by vyneer** [kennyp/asdf-golang#91]
**Describe the bug**
It seems like a ```.sha256``` file only started getting provided with the downloads [somewhere in 2016](https://go.googlesource.com/build/+/24f7399f96feb8dd2fc54f064e47a886c2f8bb4a), which leads to this plugin being unable to install versions older than that because of a failed checksum check.

**To Reproduce**
1. ```asdf install golang 1.5.3```
2. See error

**Expected behavior**
Go version 1.5.3 installs.

**Screenshots**
![image](https://user-images.githubusercontent.com/41237021/200174575-4ae6c52a-fd98-4b8a-925d-30159b6b3b00.png)

**Desktop**
 - OS: Arch Linux 6.0.7.zen1-1 amd64 
 and 
 - OS: Windows WSL 5.15.68.1-microsoft-standard-WSL2

**Additional context**
It seems like the Go team is aware of the issue, and they're planning on adding the missing checksums eventually (https://github.com/golang/go/issues/45608). They are also missing from [the go.dev/dl JSON list](https://go.dev/dl/?mode=json&include=all), but there are SHA1 checksums available on the plain https://go.dev/dl page.

Not sure what's the best way to go about fixing this, but, if possible to implement, maybe some kind of ```--skip-checksum``` flag or ```SKIP_CHECKSUM=1``` env var to bypass the check would be helpful.

**Comment by kennyp** [comment]
I think something like an `ASDF_GOLANG_SKIP_CHECKSUM` env var makes sense. I'll work on putting together a PR.
