### ISSUE TITLE
Support `go.work` for tool version

### ISSUE THREAD

**Issue by acceptto-nhumble** [kennyp/asdf-golang#98]
**Is your feature request related to a problem? Please describe.**
When using a `go.work` file to define the source location, asdf does not pick up the tool version as it would from `go.mod`

**Describe the solution you'd like**
When present use `go.work` to determine the golang version using the same logic as for `go.mod`

**Describe alternatives you've considered**
The only alternative is to define the version in `.go-version` or `.tool-versions`

**Comment by kennyp** [comment]
Closed by #100
